In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split
%matplotlib inline

In [3]:
df = pd.read_csv("/content/Breast_Cancer.csv")
df.head()

Age   Race Marital Status T Stage  N Stage 6th Stage  \
0   68  White        Married       T1      N1       IIA   
1   50  White        Married       T2      N2      IIIA   
2   58  White       Divorced       T3      N3      IIIC   
3   58  White        Married       T1      N1       IIA   
4   47  White        Married       T2      N1       IIB   

               differentiate Grade   A Stage  Tumor Size Estrogen Status  \
0      Poorly differentiated     3  Regional           4        Positive   
1  Moderately differentiated     2  Regional          35        Positive   
2  Moderately differentiated     2  Regional          63        Positive   
3      Poorly differentiated     3  Regional          18        Positive   
4      Poorly differentiated     3  Regional          41        Positive   

  Progesterone Status  Regional Node Examined  Reginol Node Positive  \
0            Positive                      24                      1   
1            Positive                      14                      5   
2            Positive                      14                      7   
3            Positive                       2                      1   
4            Positive                       3                      1   

   Survival Months Status  
0               60  Alive  
1               62  Alive  
2               75  Alive  
3               84  Alive  
4               50  Alive

In [4]:
df.shape

(4024, 16)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4024 entries, 0 to 4023
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype 
---  ------                  --------------  ----- 
 0   Age                     4024 non-null   int64 
 1   Race                    4024 non-null   object
 2   Marital Status          4024 non-null   object
 3   T Stage                 4024 non-null   object
 4   N Stage                 4024 non-null   object
 5   6th Stage               4024 non-null   object
 6   differentiate           4024 non-null   object
 7   Grade                   4024 non-null   object
 8   A Stage                 4024 non-null   object
 9   Tumor Size              4024 non-null   int64 
 10  Estrogen Status         4024 non-null   object
 11  Progesterone Status     4024 non-null   object
 12  Regional Node Examined  4024 non-null   int64 
 13  Reginol Node Positive   4024 non-null   int64 
 14  Survival Months         4024 non-null   int64 
 15  Stat

In [6]:
df.describe()

Age   Tumor Size  Regional Node Examined  \
count  4024.000000  4024.000000             4024.000000   
mean     53.972167    30.473658               14.357107   
std       8.963134    21.119696                8.099675   
min      30.000000     1.000000                1.000000   
25%      47.000000    16.000000                9.000000   
50%      54.000000    25.000000               14.000000   
75%      61.000000    38.000000               19.000000   
max      69.000000   140.000000               61.000000   

       Reginol Node Positive  Survival Months  
count            4024.000000      4024.000000  
mean                4.158052        71.297962  
std                 5.109331        22.921430  
min                 1.000000         1.000000  
25%                 1.000000        56.000000  
50%                 2.000000        73.000000  
75%                 5.000000        90.000000  
max                46.000000       107.000000

In [7]:
df.describe(include='object')

Race Marital Status T Stage  N Stage 6th Stage  \
count    4024           4024     4024    4024      4024   
unique      3              5        4       3         5   
top     White        Married       T2      N1       IIA   
freq     3413           2643     1786    2732      1305   

                    differentiate Grade   A Stage Estrogen Status  \
count                        4024  4024      4024            4024   
unique                          4     4         2               2   
top     Moderately differentiated     2  Regional        Positive   
freq                         2351  2351      3932            3755   

       Progesterone Status Status  
count                 4024   4024  
unique                   2      2  
top               Positive  Alive  
freq                  3326   3408

In [8]:
df.Grade.unique()

array(['3', '2', '1', ' anaplastic; Grade IV'], dtype=object)

In [9]:
df[df['Grade']==" anaplastic; Grade IV"]

Age   Race Marital Status T Stage  N Stage 6th Stage     differentiate  \
277    52  Black        Single        T3      N3      IIIC  Undifferentiated   
616    38  White        Married       T3      N1      IIIA  Undifferentiated   
618    37  Black        Married       T3      N1      IIIA  Undifferentiated   
767    69  White        Married       T1      N1       IIA  Undifferentiated   
1013   59  White        Single        T2      N2      IIIA  Undifferentiated   
1061   67  White        Married       T2      N3      IIIC  Undifferentiated   
1458   39  White        Single        T3      N2      IIIA  Undifferentiated   
1541   69  White        Widowed       T2      N3      IIIC  Undifferentiated   
1560   58  White        Single        T1      N2      IIIA  Undifferentiated   
1716   43  White        Married       T3      N2      IIIA  Undifferentiated   
2172   62  Black      Separated       T4      N3      IIIC  Undifferentiated   
2177   63  White        Married       T2      N1       IIB  Undifferentiated   
2246   50  White        Married       T3      N1      IIIA  Undifferentiated   
2411   57  White        Married       T1      N1       IIA  Undifferentiated   
2717   40  White        Single        T3      N1      IIIA  Undifferentiated   
3073   43  White        Married       T4      N3      IIIC  Undifferentiated   
3212   54  White       Divorced       T1      N1       IIA  Undifferentiated   
3248   45  White        Married       T1      N1       IIA  Undifferentiated   
3526   49  White        Married       T2      N1       IIB  Undifferentiated   

                      Grade   A Stage  Tumor Size Estrogen Status  \
277    anaplastic; Grade IV  Regional         100        Positive   
616    anaplastic; Grade IV  Regional          70        Positive   
618    anaplastic; Grade IV  Regional          60        Positive   
767    anaplastic; Grade IV  Regional          20        Positive   
1013   anaplastic; Grade IV  Regional          40        Negative   
1061   anaplastic; Grade IV  Regional          21        Positive   
1458   anaplastic; Grade IV  Regional          70        Positive   
1541   anaplastic; Grade IV  Regional          28        Positive   
1560   anaplastic; Grade IV  Regional          19        Negative   
1716   anaplastic; Grade IV  Regional          75        Negative   
2172   anaplastic; Grade IV  Regional          70        Positive   
2177   anaplastic; Grade IV  Regional          25        Negative   
2246   anaplastic; Grade IV  Regional          55        Positive   
2411   anaplastic; Grade IV  Regional          18        Positive   
2717   anaplastic; Grade IV  Regional          52        Positive   
3073   anaplastic; Grade IV  Regional          59        Negative   
3212   anaplastic; Grade IV  Regional          16        Positive   
3248   anaplastic; Grade IV  Regional          13        Positive   
3526   anaplastic; Grade IV  Regional          28        Positive   

     Progesterone Status  Regional Node Examined  Reginol Node Positive  \
277             Positive                      23                     17   
616             Positive                      10                      1   
618             Positive                       5                      2   
767             Positive                      17                      3   
1013            Negative                      10                      9   
1061            Positive                      25                     17   
1458            Positive                      14                      4   
1541            Positive                      14                     13   
1560            Negative                      47                      7   
1716            Negative                      10                      5   
2172            Positive                      10                     10   
2177            Positive                      10                      2   
2246            Positive                      12 

In [10]:
df["Grade"] = df["Grade"].str.replace(" anaplastic; Grade IV",'4').astype("float64")

In [11]:
df["Grade"] = df["Grade"].astype("float64")

In [12]:
df.Grade.describe()

count    4024.000000
mean        2.150596
std         0.638234
min         1.000000
25%         2.000000
50%         2.000000
75%         3.000000
max         4.000000
Name: Grade, dtype: float64

In [13]:
df.Grade.unique()

array([3., 2., 1., 4.])

In [14]:
df.describe()

Age        Grade   Tumor Size  Regional Node Examined  \
count  4024.000000  4024.000000  4024.000000             4024.000000   
mean     53.972167     2.150596    30.473658               14.357107   
std       8.963134     0.638234    21.119696                8.099675   
min      30.000000     1.000000     1.000000                1.000000   
25%      47.000000     2.000000    16.000000                9.000000   
50%      54.000000     2.000000    25.000000               14.000000   
75%      61.000000     3.000000    38.000000               19.000000   
max      69.000000     4.000000   140.000000               61.000000   

       Reginol Node Positive  Survival Months  
count            4024.000000      4024.000000  
mean                4.158052        71.297962  
std                 5.109331        22.921430  
min                 1.000000         1.000000  
25%                 1.000000        56.000000  
50%                 2.000000        73.000000  
75%                 5.000000        90.000000  
max                46.000000       107.000000

In [15]:
df.duplicated().sum()

1

In [16]:
df[df.duplicated()]

Age   Race Marital Status T Stage  N Stage 6th Stage  \
436   63  White        Married       T1      N1       IIA   

                 differentiate  Grade   A Stage  Tumor Size Estrogen Status  \
436  Moderately differentiated    2.0  Regional          17        Positive   

    Progesterone Status  Regional Node Examined  Reginol Node Positive  \
436            Positive                       9                      1   

     Survival Months Status  
436               56  Alive

In [17]:
df = df.drop_duplicates()

In [18]:
df.duplicated().sum()

0

In [19]:
df["Race"].unique()

array(['White', 'Black', 'Other'], dtype=object)

In [20]:
df[(df.Race=="Black")].head(3)

Age   Race Marital Status T Stage  N Stage 6th Stage  \
18   48  Black       Divorced       T2      N1       IIB   
43   53  Black        Single        T2      N2      IIIA   
52   60  Black        Married       T3      N1      IIIA   

                differentiate  Grade   A Stage  Tumor Size Estrogen Status  \
18  Moderately differentiated    2.0  Regional          25        Positive   
43      Poorly differentiated    3.0  Regional          23        Positive   
52      Poorly differentiated    3.0  Regional         120        Positive   

   Progesterone Status  Regional Node Examined  Reginol Node Positive  \
18            Positive                      16                      1   
43            Negative                      15                      6   
52            Negative                       7                      1   

    Survival Months Status  
18              107  Alive  
43               84  Alive  
52               86  Alive

In [21]:
df[(df.Race=="White")].head(3)

Age   Race Marital Status T Stage  N Stage 6th Stage  \
0   68  White        Married       T1      N1       IIA   
1   50  White        Married       T2      N2      IIIA   
2   58  White       Divorced       T3      N3      IIIC   

               differentiate  Grade   A Stage  Tumor Size Estrogen Status  \
0      Poorly differentiated    3.0  Regional           4        Positive   
1  Moderately differentiated    2.0  Regional          35        Positive   
2  Moderately differentiated    2.0  Regional          63        Positive   

  Progesterone Status  Regional Node Examined  Reginol Node Positive  \
0            Positive                      24                      1   
1            Positive                      14                      5   
2            Positive                      14                      7   

   Survival Months Status  
0               60  Alive  
1               62  Alive  
2               75  Alive

In [22]:
df["A Stage"].unique()

array(['Regional', 'Distant'], dtype=object)

In [23]:
df[df["A Stage"]=='Regional'].head(5)

Age   Race Marital Status T Stage  N Stage 6th Stage  \
0   68  White        Married       T1      N1       IIA   
1   50  White        Married       T2      N2      IIIA   
2   58  White       Divorced       T3      N3      IIIC   
3   58  White        Married       T1      N1       IIA   
4   47  White        Married       T2      N1       IIB   

               differentiate  Grade   A Stage  Tumor Size Estrogen Status  \
0      Poorly differentiated    3.0  Regional           4        Positive   
1  Moderately differentiated    2.0  Regional          35        Positive   
2  Moderately differentiated    2.0  Regional          63        Positive   
3      Poorly differentiated    3.0  Regional          18        Positive   
4      Poorly differentiated    3.0  Regional          41        Positive   

  Progesterone Status  Regional Node Examined  Reginol Node Positive  \
0            Positive                      24                      1   
1            Positive                      14                      5   
2            Positive                      14                      7   
3            Positive                       2                      1   
4            Positive                       3                      1   

   Survival Months Status  
0               60  Alive  
1               62  Alive  
2               75  Alive  
3               84  Alive  
4               50  Alive

In [24]:
df[df["A Stage"]=='Distant'].head()

Age   Race Marital Status T Stage  N Stage 6th Stage  \
9     69  White        Married       T4      N3      IIIC   
138   61  White        Single        T2      N3      IIIC   
167   37  White        Single        T4      N3      IIIC   
194   42  White        Single        T3      N3      IIIC   
219   50  White        Married       T3      N3      IIIC   

                 differentiate  Grade  A Stage  Tumor Size Estrogen Status  \
9          Well differentiated    1.0  Distant          32        Positive   
138  Moderately differentiated    2.0  Distant          49        Positive   
167  Moderately differentiated    2.0  Distant          70        Positive   
194  Moderately differentiated    2.0  Distant          75        Positive   
219      Poorly differentiated    3.0  Distant          75        Negative   

    Progesterone Status  Regional Node Examined  Reginol Node Positive  \
9              Positive                      21                     12   
138            Positive                      14                     10   
167            Positive                      24                     17   
194            Positive                      16                     13   
219            Negative                      27                     27   

     Survival Months Status  
9                 92  Alive  
138               53   Dead  
167              102  Alive  
194               55  Alive  
219               23   Dead

In [25]:
Categorical = df.describe(include='object')

In [26]:
Categorical.columns

Index(['Race', 'Marital Status', 'T Stage ', 'N Stage', '6th Stage',
       'differentiate', 'A Stage', 'Estrogen Status', 'Progesterone Status',
       'Status'],
      dtype='object')

In [27]:
from sklearn.preprocessing import LabelEncoder

In [28]:
le = LabelEncoder()

In [31]:
df['Race'] = le.fit_transform(df['Race'])
df['Marital Status'] = le.fit_transform(df['Marital Status'])
df['T Stage '] = le.fit_transform(df['T Stage '])
df['N Stage'] = le.fit_transform(df['N Stage'])
df['6th Stage'] = le.fit_transform(df['6th Stage'])
df['differentiate'] = le.fit_transform(df['differentiate'])
df['A Stage'] = le.fit_transform(df['A Stage'])
df['Estrogen Status'] = le.fit_transform(df['Estrogen Status'])
df['Progesterone Status'] = le.fit_transform(df['Progesterone Status'])
df['Status'] = le.fit_transform(df['Status'])

In [32]:
df['Status'].unique()

array([0, 1])

In [33]:
df['Marital Status'].unique()

array([1, 0, 3, 4, 2])

In [34]:
df.head()

Age  Race  Marital Status  T Stage   N Stage  6th Stage  differentiate  \
0   68     2               1         0        0          0              1   
1   50     2               1         1        1          2              0   
2   58     2               0         2        2          4              0   
3   58     2               1         0        0          0              1   
4   47     2               1         1        0          1              1   

   Grade  A Stage  Tumor Size  Estrogen Status  Progesterone Status  \
0    3.0        1           4                1                    1   
1    2.0        1          35                1                    1   
2    2.0        1          63                1                    1   
3    3.0        1          18                1                    1   
4    3.0        1          41                1                    1   

   Regional Node Examined  Reginol Node Positive  Survival Months  Status  
0                      24                      1               60       0  
1                      14                      5               62       0  
2                      14                      7               75       0  
3                       2                      1               84       0  
4                       3                      1               50       0

In [35]:
df.isnull().sum()

Age                       0
Race                      0
Marital Status            0
T Stage                   0
N Stage                   0
6th Stage                 0
differentiate             0
Grade                     0
A Stage                   0
Tumor Size                0
Estrogen Status           0
Progesterone Status       0
Regional Node Examined    0
Reginol Node Positive     0
Survival Months           0
Status                    0
dtype: int64

In [37]:
X = df.drop(['Status'], axis=1)
y = df['Status']

In [38]:
X.columns

Index(['Age', 'Race', 'Marital Status', 'T Stage ', 'N Stage', '6th Stage',
       'differentiate', 'Grade', 'A Stage', 'Tumor Size', 'Estrogen Status',
       'Progesterone Status', 'Regional Node Examined',
       'Reginol Node Positive', 'Survival Months'],
      dtype='object')

In [40]:
from sklearn.model_selection import train_test_split

In [41]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.1,random_state=42)

In [42]:
from sklearn.linear_model import LogisticRegression

log_reg = LogisticRegression()

log_reg.fit(X_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [43]:
y_pred_test = log_reg.predict(X_test)
y_pred_test

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [44]:
log_reg.coef_

array([[ 0.02815538, -0.06017154,  0.04514293,  0.40791192,  0.33642118,
        -0.03096051,  0.00446099,  0.43917992,  0.03120651, -0.00256959,
        -0.35408477, -0.58480626, -0.0318331 ,  0.07242535, -0.05985654]])

In [46]:
log_reg.intercept_

array([-0.03631491])

In [59]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, recall_score, precision_score, f1_score
accuracy = accuracy_score(y_test, y_pred_test)
accuracy

0.9156327543424317

In [60]:

conf_matrix = confusion_matrix(y_test, y_pred_test)

print('Confusion matrix\n\n', conf_matrix)

print('\nTrue positive = ', conf_matrix[1,1])
print('\nTrue Negative = ', conf_matrix[0,0])
print('\nFalse positive = ', conf_matrix[0,1])
print('\nFalse Negative = ', conf_matrix[1,0])

Confusion matrix

 [[337   6]
 [ 28  32]]

True positive =  32

True Negative =  337

False positive =  6

False Negative =  28


In [61]:
print(classification_report(y_test, y_pred_test))

              precision    recall  f1-score   support

           0       0.92      0.98      0.95       343
           1       0.84      0.53      0.65        60

    accuracy                           0.92       403
   macro avg       0.88      0.76      0.80       403
weighted avg       0.91      0.92      0.91       403

